import { Geist, Geist_Mono, Plus_Jakarta_Sans, Fragment_Mono } from "next/font/google";
import "./globals.css";

import dynamic from 'next/dynamic'
import ClientFogWrapper from "@/components/react-three/ClientFogWrapper";
import TransitionOverlay from "@/components/PageTransitions/TransitionOverlay";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const fragmentMono = Fragment_Mono({
  variable: "--font-fragment-mono",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${plusJakartaSans.variable} ${fragmentMono.variable} antialiased`}
    >
      <TransitionOverlay />
      <body className="min-h-full flex flex-col"><ClientFogWrapper />{children}</body>
      
    </html>
  );
}
